// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawler_am.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CrawlerConfigRequest struct {
	CheckList            []*CheckRequest `protobuf:"bytes,1,rep,name=checkList,proto3" json:"checkList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CrawlerConfigRequest) Reset()         { *m = CrawlerConfigRequest{} }
func (m *CrawlerConfigRequest) String() string { return proto.CompactTextString(m) }
func (*CrawlerConfigRequest) ProtoMessage()    {}
func (*CrawlerConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_crawler_am_8af9dd06beedd711, []int{0}
}
func (m *CrawlerConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlerConfigRequest.Unmarshal(m, b)
}
func (m *CrawlerConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlerConfigRequest.Marshal(b, m, deterministic)
}
func (dst *CrawlerConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlerConfigRequest.Merge(dst, src)
}
func (m *CrawlerConfigRequest) XXX_Size() int {
	return xxx_messageInfo_CrawlerConfigRequest.Size(m)
}
func (m *CrawlerConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlerConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlerConfigRequest proto.InternalMessageInfo

func (m *CrawlerConfigRequest) GetCheckList() []*CheckRequest {
	if m != nil {
		return m.CheckList
	}
	return nil
}

type CheckRequest struct {
	// apkName: 查找的app name
	PackageName string `protobuf:"bytes,1,opt,name=packageName,proto3" json:"packageName,omitempty"`
	// url: 该项目apkmirror所在页面
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// version: 当前版本
	LastUploadTime       string   `protobuf:"bytes,3,opt,name=lastUploadTime,proto3" json:"lastUploadTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_crawler_am_8af9dd06beedd711, []int{1}
}
func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (dst *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(dst, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

func (m *CheckRequest) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *CheckRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CheckRequest) GetLastUploadTime() string {
	if m != nil {
		return m.LastUploadTime
	}
	return ""
}

type CrawlerConfigReply struct {
	AppInfoList          []*ApkDetailReply `protobuf:"bytes,1,rep,name=appInfoList,proto3" json:"appInfoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CrawlerConfigReply) Reset()         { *m = CrawlerConfigReply{} }
func (m *CrawlerConfigReply) String() string { return proto.CompactTextString(m) }
func (*CrawlerConfigReply) ProtoMessage()    {}
func (*CrawlerConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_crawler_am_8af9dd06beedd711, []int{2}
}
func (m *CrawlerConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlerConfigReply.Unmarshal(m, b)
}
func (m *CrawlerConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlerConfigReply.Marshal(b, m, deterministic)
}
func (dst *CrawlerConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlerConfigReply.Merge(dst, src)
}
func (m *CrawlerConfigReply) XXX_Size() int {
	return xxx_messageInfo_CrawlerConfigReply.Size(m)
}
func (m *CrawlerConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlerConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlerConfigReply proto.InternalMessageInfo

func (m *CrawlerConfigReply) GetAppInfoList() []*ApkDetailReply {
	if m != nil {
		return m.AppInfoList
	}
	return nil
}

type CrawlerTaskRequest struct {
	// package:包名
	PackageName string `protobuf:"bytes,1,opt,name=packageName,proto3" json:"packageName,omitempty"`
	// 页码
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// 每页显示数目
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrawlerTaskRequest) Reset()         { *m = CrawlerTaskRequest{} }
func (m *CrawlerTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CrawlerTaskRequest) ProtoMessage()    {}
func (*CrawlerTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_crawler_am_8af9dd06beedd711, []int{3}
}
func (m *CrawlerTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlerTaskRequest.Unmarshal(m, b)
}
func (m *CrawlerTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlerTaskRequest.Marshal(b, m, deterministic)
}
func (dst *CrawlerTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlerTaskRequest.Merge(dst, src)
}
func (m *CrawlerTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CrawlerTaskRequest.Size(m)
}
func (m *CrawlerTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlerTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlerTaskRequest proto.InternalMessageInfo

func (m *CrawlerTaskRequest) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *CrawlerTaskRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *CrawlerTaskRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type CrawlerTaskReply struct {
	// apk 详情
	AppInfoList []*ApkDetailReply `protobuf:"bytes,1,rep,name=appInfoList,proto3" json:"appInfoList,omitempty"`
	// apk  总数
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrawlerTaskReply) Reset()         { *m = CrawlerTaskReply{} }
func (m *CrawlerTaskReply) String() string { return proto.CompactTextString(m) }
func (*CrawlerTaskReply) ProtoMessage()    {}
func (*CrawlerTaskReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_crawler_am_8af9dd06beedd711, []int{4}
}
func (m *CrawlerTaskReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlerTaskReply.Unmarshal(m, b)
}
func (m *CrawlerTaskReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlerTaskReply.Marshal(b, m, deterministic)
}
func (dst *CrawlerTaskReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlerTaskReply.Merge(dst, src)
}
func (m *CrawlerTaskReply) XXX_Size() int {
	return xxx_messageInfo_CrawlerTaskReply.Size(m)
}
func (m *CrawlerTaskReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlerTaskReply.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlerTaskReply proto.InternalMessageInfo

func (m *CrawlerTaskReply) GetAppInfoList() []*ApkDetailReply {
	if m != nil {
		return m.AppInfoList
	}
	return nil
}

func (m *CrawlerTaskReply) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ApkDetailReply struct {
	// 唯一Id
	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// apk 包名
	QueryName string `protobuf:"bytes,2,opt,name=queryName,proto3" json:"queryName,omitempty"`
	// apk 名称
	ApkName string `protobuf:"bytes,3,opt,name=apkName,proto3" json:"apkName,omitempty"`
	// apk 图标
	ApkIcon string `protobuf:"bytes,4,opt,name=apkIcon,proto3" json:"apkIcon,omitempty"`
	// apk 版本名
	ApkVersion string `protobuf:"bytes,5,opt,name=apkVersion,proto3" json:"apkVersion,omitempty"`
	// apk 上传时间
	ApkUpload string `protobuf:"bytes,6,opt,name=apkUpload,proto3" json:"apkUpload,omitempty"`
	// apk 安装包大小
	ApkSize string `protobuf:"bytes,7,opt,name=apkSize,proto3" json:"apkSize,omitempty"`
	// apk 下载次数
	Downloads string `protobuf:"bytes,8,opt,name=downloads,proto3" json:"downloads,omitempty"`
	// apk 下载链接 同一个apk有不同的变种，会有多个url
	ApkLink []*DownloadLink `protobuf:"bytes,9,rep,name=apkLink,proto3" json:"apkLink,omitempty"`
	// apk 查询时间
	UpdateTime           string   `protobuf:"bytes,10,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApkDetailReply) Reset()         { *m = ApkDetailReply{} }
func (m *ApkDetailReply) String() string { return proto.CompactTextString(m) }
func (*ApkDetailReply) ProtoMessage()    {}
func (*ApkDetailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_crawler_am_8af9dd06beedd711, []int{5}
}
func (m *ApkDetailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApkDetailReply.Unmarshal(m, b)
}
func (m *ApkDetailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApkDetailReply.Marshal(b, m, deterministic)
}
func (dst *ApkDetailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApkDetailReply.Merge(dst, src)
}
func (m *ApkDetailReply) XXX_Size() int {
	return xxx_messageInfo_ApkDetailReply.Size(m)
}
func (m *ApkDetailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ApkDetailReply.DiscardUnknown(m)
}

var xxx_messageInfo_ApkDetailReply proto.InternalMessageInfo

func (m *ApkDetailReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApkDetailReply) GetQueryName() string {
	if m != nil {
		return m.QueryName
	}
	return ""
}

func (m *ApkDetailReply) GetApkName() string {
	if m != nil {
		return m.ApkName
	}
	return ""
}

func (m *ApkDetailReply) GetApkIcon() string {
	if m != nil {
		return m.ApkIcon
	}
	return ""
}

func (m *ApkDetailReply) GetApkVersion() string {
	if m != nil {
		return m.ApkVersion
	}
	return ""
}

func (m *ApkDetailReply) GetApkUpload() string {
	if m != nil {
		return m.ApkUpload
	}
	return ""
}

func (m *ApkDetailReply) GetApkSize() string {
	if m != nil {
		return m.ApkSize
	}
	return ""
}

func (m *ApkDetailReply) GetDownloads() string {
	if m != nil {
		return m.Downloads
	}
	return ""
}

func (m *ApkDetailReply) GetApkLink() []*DownloadLink {
	if m != nil {
		return m.ApkLink
	}
	return nil
}

func (m *ApkDetailReply) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type ApkDownloadUploadeRequest struct {
	// package:包名
	Package string `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	// link: 图片的原始连接
	Link                 string   `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApkDownloadUploadeRequest) Reset()         { *m = ApkDownloadUploadeRequest{} }
func (m *ApkDownloadUploadeRequest) String() string { return proto.CompactTextString(m) }
func (*ApkDownloadUploadeRequest) ProtoMessage()    {}
func (*ApkDownloadUploadeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_crawler_am_8af9dd06beedd711, []int{6}
}
func (m *ApkDownloadUploadeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApkDownloadUploadeRequest.Unmarshal(m, b)
}
func (m *ApkDownloadUploadeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApkDownloadUploadeRequest.Marshal(b, m, deterministic)
}
func (dst *ApkDownloadUploadeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApkDownloadUploadeRequest.Merge(dst, src)
}
func (m *ApkDownloadUploadeRequest) XXX_Size() int {
	return xxx_messageInfo_ApkDownloadUploadeRequest.Size(m)
}
func (m *ApkDownloadUploadeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApkDownloadUploadeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApkDownloadUploadeRequest proto.InternalMessageInfo

func (m *ApkDownloadUploadeRequest) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *ApkDownloadUploadeRequest) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

type ApkDownloadUploadReply struct {
	AppInfoList          []*ApkDetailReply `protobuf:"bytes,1,rep,name=appInfoList,proto3" json:"appInfoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ApkDownloadUploadReply) Reset()         { *m = ApkDownloadUploadReply{} }
func (m *ApkDownloadUploadReply) String() string { return proto.CompactTextString(m) }
func (*ApkDownloadUploadReply) ProtoMessage()    {}
func (*ApkDownloadUploadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_crawler_am_8af9dd06beedd711, []int{7}
}
func (m *ApkDownloadUploadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApkDownloadUploadReply.Unmarshal(m, b)
}
func (m *ApkDownloadUploadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApkDownloadUploadReply.Marshal(b, m, deterministic)
}
func (dst *ApkDownloadUploadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApkDownloadUploadReply.Merge(dst, src)
}
func (m *ApkDownloadUploadReply) XXX_Size() int {
	return xxx_messageInfo_ApkDownloadUploadReply.Size(m)
}
func (m *ApkDownloadUploadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ApkDownloadUploadReply.DiscardUnknown(m)
}

var xxx_messageInfo_ApkDownloadUploadReply proto.InternalMessageInfo

func (m *ApkDownloadUploadReply) GetAppInfoList() []*ApkDetailReply {
	if m != nil {
		return m.AppInfoList
	}
	return nil
}

type DownloadLink struct {
	// apk相同版本变体名
	VariantName string `protobuf:"bytes,1,opt,name=variantName,proto3" json:"variantName,omitempty"`
	// 下载链接
	DownloadUrl string `protobuf:"bytes,2,opt,name=downloadUrl,proto3" json:"downloadUrl,omitempty"`
	// 版本号
	VersionCode          string   `protobuf:"bytes,3,opt,name=versionCode,proto3" json:"versionCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadLink) Reset()         { *m = DownloadLink{} }
func (m *DownloadLink) String() string { return proto.CompactTextString(m) }
func (*DownloadLink) ProtoMessage()    {}
func (*DownloadLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_crawler_am_8af9dd06beedd711, []int{8}
}
func (m *DownloadLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadLink.Unmarshal(m, b)
}
func (m *DownloadLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadLink.Marshal(b, m, deterministic)
}
func (dst *DownloadLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadLink.Merge(dst, src)
}
func (m *DownloadLink) XXX_Size() int {
	return xxx_messageInfo_DownloadLink.Size(m)
}
func (m *DownloadLink) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadLink.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadLink proto.InternalMessageInfo

func (m *DownloadLink) GetVariantName() string {
	if m != nil {
		return m.VariantName
	}
	return ""
}

func (m *DownloadLink) GetDownloadUrl() string {
	if m != nil {
		return m.DownloadUrl
	}
	return ""
}

func (m *DownloadLink) GetVersionCode() string {
	if m != nil {
		return m.VersionCode
	}
	return ""
}

func init() {
	proto.RegisterType((*CrawlerConfigRequest)(nil), "protos.CrawlerConfigRequest")
	proto.RegisterType((*CheckRequest)(nil), "protos.CheckRequest")
	proto.RegisterType((*CrawlerConfigReply)(nil), "protos.CrawlerConfigReply")
	proto.RegisterType((*CrawlerTaskRequest)(nil), "protos.CrawlerTaskRequest")
	proto.RegisterType((*CrawlerTaskReply)(nil), "protos.CrawlerTaskReply")
	proto.RegisterType((*ApkDetailReply)(nil), "protos.ApkDetailReply")
	proto.RegisterType((*ApkDownloadUploadeRequest)(nil), "protos.ApkDownloadUploadeRequest")
	proto.RegisterType((*ApkDownloadUploadReply)(nil), "protos.ApkDownloadUploadReply")
	proto.RegisterType((*DownloadLink)(nil), "protos.DownloadLink")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CrawlerAMServiceClient is the client API for CrawlerAMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CrawlerAMServiceClient interface {
	CheckUpdate(ctx context.Context, in *CrawlerConfigRequest, opts ...grpc.CallOption) (*CrawlerConfigReply, error)
	CollectHistory(ctx context.Context, in *CrawlerTaskRequest, opts ...grpc.CallOption) (*CrawlerTaskReply, error)
}

type crawlerAMServiceClient struct {
	cc *grpc.ClientConn
}

func NewCrawlerAMServiceClient(cc *grpc.ClientConn) CrawlerAMServiceClient {
	return &crawlerAMServiceClient{cc}
}

func (c *crawlerAMServiceClient) CheckUpdate(ctx context.Context, in *CrawlerConfigRequest, opts ...grpc.CallOption) (*CrawlerConfigReply, error) {
	out := new(CrawlerConfigReply)
	err := c.cc.Invoke(ctx, "/protos.CrawlerAMService/CheckUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlerAMServiceClient) CollectHistory(ctx context.Context, in *CrawlerTaskRequest, opts ...grpc.CallOption) (*CrawlerTaskReply, error) {
	out := new(CrawlerTaskReply)
	err := c.cc.Invoke(ctx, "/protos.CrawlerAMService/CollectHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlerAMServiceServer is the server API for CrawlerAMService service.
type CrawlerAMServiceServer interface {
	CheckUpdate(context.Context, *CrawlerConfigRequest) (*CrawlerConfigReply, error)
	CollectHistory(context.Context, *CrawlerTaskRequest) (*CrawlerTaskReply, error)
}

func RegisterCrawlerAMServiceServer(s *grpc.Server, srv CrawlerAMServiceServer) {
	s.RegisterService(&_CrawlerAMService_serviceDesc, srv)
}

func _CrawlerAMService_CheckUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlerConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerAMServiceServer).CheckUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.CrawlerAMService/CheckUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerAMServiceServer).CheckUpdate(ctx, req.(*CrawlerConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrawlerAMService_CollectHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlerTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerAMServiceServer).CollectHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.CrawlerAMService/CollectHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerAMServiceServer).CollectHistory(ctx, req.(*CrawlerTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CrawlerAMService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.CrawlerAMService",
	HandlerType: (*CrawlerAMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUpdate",
			Handler:    _CrawlerAMService_CheckUpdate_Handler,
		},
		{
			MethodName: "CollectHistory",
			Handler:    _CrawlerAMService_CollectHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crawler_am.proto",
}

func init() { proto.RegisterFile("crawler_am.proto", fileDescriptor_crawler_am_8af9dd06beedd711) }

var fileDescriptor_crawler_am_8af9dd06beedd711 = []byte{
	// 528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xb1, 0x6e, 0xdb, 0x30,
	0x10, 0xad, 0xed, 0x38, 0x8e, 0xcf, 0x81, 0x61, 0x1c, 0x8c, 0x80, 0x35, 0x82, 0xc2, 0xd0, 0x50,
	0x64, 0xf2, 0xe0, 0x2e, 0x5d, 0x03, 0x67, 0x88, 0x8a, 0x34, 0x83, 0x12, 0x77, 0x2d, 0x18, 0x89,
	0x76, 0x59, 0xd1, 0x22, 0x23, 0x51, 0x09, 0xdc, 0x1f, 0xea, 0x2f, 0xf4, 0xf3, 0x0a, 0x92, 0x92,
	0x4c, 0xbb, 0xe9, 0x10, 0x64, 0x92, 0xee, 0xbd, 0x77, 0xc7, 0xc7, 0xe3, 0x91, 0x30, 0x8a, 0x73,
	0xfa, 0x2c, 0x58, 0xfe, 0x9d, 0x6e, 0x66, 0x2a, 0x97, 0x5a, 0xe2, 0xb1, 0xfd, 0x14, 0xc1, 0x17,
	0x18, 0x2f, 0x1c, 0xb7, 0x90, 0xd9, 0x8a, 0xaf, 0x23, 0xf6, 0x58, 0xb2, 0x42, 0xe3, 0x1c, 0xfa,
	0xf1, 0x0f, 0x16, 0xa7, 0x37, 0xbc, 0xd0, 0xa4, 0x35, 0xed, 0x5c, 0x0c, 0xe6, 0x63, 0x97, 0x5a,
	0xcc, 0x16, 0x86, 0xa8, 0x84, 0xd1, 0x4e, 0x16, 0xfc, 0x84, 0x53, 0x9f, 0xc2, 0x29, 0x0c, 0x14,
	0x8d, 0x53, 0xba, 0x66, 0xb7, 0x74, 0xc3, 0x48, 0x6b, 0xda, 0xba, 0xe8, 0x47, 0x3e, 0x84, 0x23,
	0xe8, 0x94, 0xb9, 0x20, 0x6d, 0xcb, 0x98, 0x5f, 0xfc, 0x08, 0x43, 0x41, 0x0b, 0xbd, 0x54, 0x42,
	0xd2, 0xe4, 0x9e, 0x6f, 0x18, 0xe9, 0x58, 0xf2, 0x00, 0x0d, 0x6e, 0x01, 0x0f, 0x7c, 0x2b, 0xb1,
	0xc5, 0xcf, 0x30, 0xa0, 0x4a, 0x85, 0xd9, 0x4a, 0x7a, 0xbe, 0xcf, 0x6a, 0xdf, 0x97, 0x2a, 0xbd,
	0x62, 0x9a, 0x72, 0x61, 0xc5, 0x91, 0x2f, 0x0d, 0x56, 0x4d, 0xbd, 0x7b, 0x5a, 0xbc, 0x62, 0x07,
	0x08, 0x47, 0x8a, 0xae, 0x99, 0xdd, 0x42, 0x37, 0xb2, 0xff, 0x38, 0x81, 0x13, 0xf3, 0xbd, 0xe3,
	0xbf, 0x9c, 0xfb, 0x6e, 0xd4, 0xc4, 0xc1, 0x03, 0x8c, 0xf6, 0xd6, 0x79, 0x93, 0x6b, 0x1c, 0x43,
	0x37, 0x96, 0x65, 0xa6, 0xab, 0xe5, 0x5d, 0x10, 0xfc, 0x69, 0xc3, 0x70, 0x3f, 0x0b, 0x87, 0xd0,
	0x0e, 0x93, 0xca, 0x7f, 0x3b, 0x4c, 0xf0, 0x1c, 0xfa, 0x8f, 0x25, 0xcb, 0xb7, 0x76, 0x5b, 0xae,
	0xfd, 0x3b, 0x00, 0x09, 0xf4, 0xa8, 0x4a, 0x2d, 0xe7, 0xba, 0x5f, 0x87, 0x15, 0x13, 0xc6, 0x32,
	0x23, 0x47, 0x0d, 0x63, 0x42, 0xfc, 0x00, 0x40, 0x55, 0xfa, 0x8d, 0xe5, 0x05, 0x97, 0x19, 0xe9,
	0x5a, 0xd2, 0x43, 0xcc, 0x8a, 0x54, 0xa5, 0xee, 0x04, 0xc9, 0xb1, 0x5b, 0xb1, 0x01, 0xaa, 0xba,
	0xb6, 0x63, 0xbd, 0xa6, 0xae, 0x09, 0x4d, 0x5e, 0x22, 0x9f, 0x33, 0xa3, 0x2a, 0xc8, 0x89, 0xcb,
	0x6b, 0x00, 0x9c, 0xd9, 0xbc, 0x1b, 0x9e, 0xa5, 0xa4, 0xbf, 0x3f, 0xa4, 0x57, 0x95, 0xc6, 0x70,
	0x51, 0x2d, 0x32, 0x2e, 0x4b, 0x95, 0x50, 0xcd, 0xec, 0x68, 0x81, 0x73, 0xb9, 0x43, 0x82, 0x10,
	0xde, 0x9b, 0xce, 0x55, 0xb9, 0xce, 0x1c, 0xab, 0xa7, 0x81, 0x40, 0xaf, 0x3a, 0xfa, 0xaa, 0x93,
	0x75, 0x68, 0xa6, 0x40, 0x18, 0x0f, 0xae, 0x93, 0xf6, 0x3f, 0x88, 0xe0, 0xec, 0x9f, 0x52, 0x6f,
	0x9d, 0x52, 0x0d, 0xa7, 0xfe, 0xbe, 0xcc, 0x7c, 0x3e, 0xd1, 0x9c, 0xd3, 0x4c, 0xfb, 0xf3, 0xe9,
	0x41, 0x46, 0x51, 0x77, 0x6b, 0xd9, 0xdc, 0x34, 0x1f, 0xb2, 0x35, 0xdc, 0x19, 0x2d, 0x64, 0x52,
	0x1f, 0xb8, 0x0f, 0xcd, 0x7f, 0xb7, 0x9a, 0xa1, 0xbd, 0xfc, 0x7a, 0xc7, 0xf2, 0x27, 0x1e, 0x33,
	0x0c, 0x61, 0x60, 0x2f, 0xfb, 0xd2, 0x36, 0x0f, 0xcf, 0x9b, 0xc7, 0xe1, 0x85, 0xd7, 0x64, 0x32,
	0xf9, 0x0f, 0xab, 0xc4, 0x36, 0x78, 0x87, 0xd7, 0x30, 0x5c, 0x48, 0x21, 0x58, 0xac, 0xaf, 0x79,
	0xa1, 0x65, 0xbe, 0xc5, 0x43, 0xbd, 0x77, 0x27, 0x27, 0xe4, 0x45, 0xce, 0x56, 0x7a, 0x70, 0xaf,
	0xda, 0xa7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xaa, 0xc3, 0x9b, 0xf0, 0x04, 0x00, 0x00,
}
